### ISSUE TITLE
`ids` isn't the only valid "list of values to search for" parameter

### ISSUE THREAD

**Issue by AWegnerGitHub** [AWegnerGitHub/stackapi#19]
Not all end points use `ids` to identify a list of elements to search for. The `tags` end points are examples of this:

[`/tags/{tags}/info`](http://api.stackexchange.com/docs/tags-by-name)

Related #18

**Comment by AWegnerGitHub** [comment]
Potential idea:

Any parameter that is passed in as a list will replace the section of the end point that is a place holder (or be tacked onto the end in the case of something like `users` vs `users/{}/comments`)

If this is the route taken, only 1 parameter can be a list. If more than 1 list is passed, an error needs to be thrown.

**Comment by ArtOfCode-** [comment]
This might be a potential approach:

If you have a `data` dictionary, iterate over it. If you find any of the parameter names in the route URL, replace them with the value (lists can be semicolon-joined).
