### ISSUE TITLE
Fetch query with string kwargs throws an error when special char is involved

### ISSUE THREAD

**Issue by martinapugliese** [AWegnerGitHub/stackapi#27]
A call like

```
so = StackAPI('stackoverflow', key='<my_key>')
a = so.fetch('tags/{tags}/synonyms', tags=['c#'])
```

throws a `StackAPIError` with no error message. This is due to the hash char. 
From the StackOverflow API UI it works instead. 

Tried encoding it with same result. Any way to go round this, or can it have a fix?

**Comment by ArtOfCode-** [comment]
What happens if you try `tags=['c%23']`?

**Comment by martinapugliese** [comment]
@ArtOfCode- Yet again the same error!

**Comment by AWegnerGitHub** [comment]
I've pushed a change to properly encode these parameters. 

I've also pushed the change to PyPI (version 0.1.8). You should be able to pull the update via:

    pip install -U stackapi

---

The example provided should return 6 items, which the [API seems to agree with](http://api.stackexchange.com/docs/synonyms-by-tags#order=desc&sort=creation&tags=c%23&filter=!9YdnSPuG8&site=stackoverflow&run=true).

**Comment by martinapugliese** [comment]
Works like a charm, thank you! Closing this issue.
