### ISSUE TITLE
Extract body of answers/questions

### ISSUE THREAD

**Issue by AbAw9** [AWegnerGitHub/stackapi#30]
Hi,

I am new to stackAPI. I wish to extract the body of the answers and questions. Could you please help me with it. Thanks

**Comment by AWegnerGitHub** [comment]
StackAPI uses the `default` filter provided by Stack Exchange by default. These filters don't include the `body` or `body_markdown` fields. However, you can pass a new filter to your `fetch()` calls that will include these fields.

The filters can be generated from the Stack Exchange API docs for the endpoint you are using. The example below hits the [`questions`](http://api.stackexchange.com/docs/questions#order=desc&sort=activity&filter=!9YdnSIN*P&site=stackoverflow&run=true) endpoint. The example is a slight modification from the one of the [advanced usage examples](http://stackapi.readthedocs.io/en/latest/user/advanced.html#calling-fetch-with-various-api-parameters) in the StackAPI docs. Notice the addition of the `filter` parameter.

```
from stackapi import StackAPI
SITE = StackAPI('stackoverflow')
questions = SITE.fetch('questions', 
    fromdate=1457136000, 
    todate=1457222400, 
    min=20, 
    tagged='python', 
    sort='votes', 
    filter='!9YdnSIN*P')
```

`questions` will now contain two additional parameters for each item in the `items` list. These will be `body` and `body_markdown`.

**Comment by AbAw9** [comment]
thank you, it works for the questions.

**Comment by AbAw9** [comment]
Hi,

is there a documentation for this filter (filter='!9YdnSIN*P')?

thanks

**Comment by AWegnerGitHub** [comment]
Filter documentation can be found on the [Stack Exchange docs](http://api.stackexchange.com/docs/filters). 

There is also a blog series by one of the Stack Exchange developers on how the API filters work:

- https://kevinmontrose.com/2012/01/06/stack-exchange-api-v2-0-filters/
- https://kevinmontrose.com/2012/01/11/stack-exchange-api-v2-0-implementing-filters/
- https://kevinmontrose.com/2012/02/08/stack-exchange-api-v2-0-safety/

---

The short version though, is to visit the end point documentation you want to use. For the example above, go to [`questions`](http://api.stackexchange.com/docs/questions). Toward the bottom, where you can test the API call, there is a **Filter** drop down. 

From this drop down you can select the fields you want to appear on your response. Check or uncheck the fields. Click *Save*. The filter will now appear in bold at the top of the drop down. Copy and paste that bold filter and you can use that in your code.

_Note_: The filter is different for each end point. You'll need to repeat the above steps for each different end point to get the fields you want and expect to be returned.

**Comment by AbAw9** [comment]
perfect, thanks a lot. :)
appreciate it...
