### ISSUE TITLE
Feature Request: Asynchronous Monitoring of endpoints.

### ISSUE THREAD

**Issue by Hyperclaw79** [AWegnerGitHub/stackapi#32]
Currently, to get the latest data from an endpoint, for example, questions, we need to poll it at regular intervals using the API. It would be helpful to have a function that could monitor an endpoint (provided with kwargs to limit the query to a specific use case) from time to time automatically and notify the user upon being updated. I wish SO has a streaming API like Twitter but unfortunately it doesn't. So why not make our own? Instead of having the users to add these extra lines of code for polling, make a function called monitor which will do the same.

Since it is a monitoring functionality, it would be better if it was async or at least runs on a background thread to prevent blocking of the normal commands.

**Comment by AWegnerGitHub** [comment]
This would eat your API quota pretty quickly. We'd still have to poll that end point because it isn't streaming and each poll would count against your quota.

**Comment by Hyperclaw79** [comment]
Hmm I see. So the only way is to manually send a request once per two hours to stay within the rate limits. 😟 
Thanks anyway.
