### ISSUE TITLE
Using filter='total' results in KeyError

### ISSUE THREAD

**Issue by tylere** [AWegnerGitHub/stackapi#33]
I am trying to replicate a total count query that is available in the StackExchange API, using the total [filter](https://api.stackexchange.com/docs/filters).  For example: 
http://api.stackexchange.com/2.2/questions?site=gis&filter=total

Example StackAPI code is:

```
from stackapi import StackAPI
SITE = StackAPI('gis')
result = SITE.fetch(
    'questions',
    filter='total'
)
result
```
which results in a KeyError:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-73-dad27c0670d8> in <module>()
      3 result = SITE.fetch(
      4     'questions',
----> 5     filter='total'
      6 )
      7 result

/usr/local/lib/python3.6/dist-packages/stackapi/stackapi.py in fetch(self, endpoint, page, key, filter, **kwargs)
    225         r = []
    226         for d in data:
--> 227             r.extend(d['items'])
    228         result = {'backoff': backoff,
    229                   'has_more': data[-1]['has_more'],

KeyError: 'items'
```

**Comment by AWegnerGitHub** [comment]
I am sorry for the delay in getting back to you. I've taken a look at this and see this is an over sight on my part in regard to some of the built in filters. They don't all return the expected key. Specifically, this call is only returning 

```
{"total":107676}
```

Let me figure out the best way to handle this and get it fixed.

**Comment by AWegnerGitHub** [comment]
The issue is that the `total` filter (and countless other custom filters) don't have the keys StackAPI is expecting. In this case, it was missing `items`, `has_more`, `quota_max` and `quota_remaining`. 

I can add these to the wrapper with defaults like so:

```
>>> SITE = StackAPI('gis')
>>> result = SITE.fetch(
...     'questions',
...     filter='total'
... )
>>> result
{'page': 1, 'total': 107677, 'items': [], 'has_more': False, 'quota_remaining': -1, 'quota_max': -1, 'backoff': 0}
```

My question to you is, are the two negative values on the `quota_*` fields acceptable?

**Comment by tylere** [comment]
Sure, that would be fine for my use case.

**Comment by tylere** [comment]
Confirming that the 0.1.12 release works for me.
Thanks!
