### ISSUE TITLE
Error when providing list of users to users/ids endpoint

### ISSUE THREAD

**Issue by mrs-aleksandra** [AWegnerGitHub/stackapi#38]
I am trying to retrieve list of users ids from answers. 
`SITE = StackAPI('stackoverflow')`
`SITE.page_size = 10`
`SITE.max_pages = 1`
`answers = SITE.fetch('answers', sort ='votes')`
`users = [answers['items'][i]['owner']['user_id'] for i in range(len(answers['items']))]`

I managed to create a list of users, but when I want to fetch them with the following line of code
`data = SITE.fetch('users/{}', ids=users)`
I receive the following error
`stackapi.stackapi.StackAPIError: ('https://api.stackexchange.com/2.2/users/%7B%7D/922184;62130;95592;14113;8985;9951;92315;394487;613430;22656/?pagesize=10&page=1&filter=default&site=stackoverflow', 404, 'no_method', 'no method found with this name')`

What could be the problem?

**Comment by ArtOfCode-** [comment]
The URL you're requesting is literally `https://api.stackexchange.com/2.2/users/{}/922184;62130;95592;14113;8985;9951;92315;394487;613430;22656/?pagesize=10&page=1&filter=default&site=stackoverflow`. The error is correct: there's no method called `users/{}`.

You need to format the `{}` string to replace it with the IDs:

```python
SITE.fetch('users/{}'.format(users))
```

**Comment by mrs-aleksandra** [comment]
> 
> 
> The URL you're requesting is literally `https://api.stackexchange.com/2.2/users/{}/922184;62130;95592;14113;8985;9951;92315;394487;613430;22656/?pagesize=10&page=1&filter=default&site=stackoverflow`. The error is correct: there's no method called `users/{}`.
> 
> You need to format the `{}` string to replace it with the IDs:
> 
> ```python
> SITE.fetch('users/{}'.format(users))
> ```

Yes, I see that URL is faulty. But the syntax I use is from the official package documentation. I already tried to format the string hoping that it will fix URL but I receive another error...
`stackapi.stackapi.StackAPIError: ('https://api.stackexchange.com/2.2/users/[922184,%2062130,%2095592,%2014113,%208985,%209951,%2092315,%20394487,%20613430,%2022656]/?pagesize=10&page=1&filter=default&site=stackoverflow', 404, 'no_method', 'no method found with this name')`

This is how the correct URL should look like
`/2.2/users/922184,62130,95592,14113,8985,9951,92315,394487,613430,22656?order=desc&sort=reputation&site=stackoverflow`
but I have no idea how to get it because following the official package documentation method doesn't work.

Thanks for the answer though! Hoping for solution

**Comment by ArtOfCode-** [comment]
Oh, hah. My format example was wrong. If you hit this sort of thing again, you'll want this:

```python
SITE.fetch('users/{}'.format(users.join(';')))
```
