### ISSUE TITLE
Support for StackOverflow enterprise

### ISSUE THREAD

**Issue by dkmiller** [AWegnerGitHub/stackapi#39]
I'm raising this as an issue not because I think there's anything wrong with StackAPI, but because I felt it would be rude to "butt in" with a pull request.

If I get consensus from the package owner, I'm happy to help implementing this.

Currently, the `StackAPI` class hardcodes the "base URL" for the StackExchange API to point at the "public" StackExchange (in [stackapy.py](https://github.com/AWegnerGitHub/stackapi/blob/master/stackapi/stackapi.py)):

```python
self._base_url = 'https://api.stackexchange.com/{}/'.format(version)
```

However, StackExchange sells an [enterprise variant](https://stackoverflow.com/teams) (distinct from "StackOverflow for Teams") &mdash; which allows corporations to self-host an instance of StackOverflow. For such corporations, the base URL will look something like `stackoverflow.myenterprise.com`, and all request will need a header `X-API-Key: api_key` (or `key` query parameter).

It seems like a reasonably straightforward update to the `StackAPI` constructor to accept kwargs for the base URL and "authentication key" (I see there's already a class variable `_api_key`). The default values for these would be `https://api.stackexchange.com` and `None`, respectively. If they **are** set, then `__init__` would set the base URL appropriately, and the `fetch` method could add the appropriate header.

Thoughts?

**Comment by AWegnerGitHub** [comment]
That sounds like a great update. Unfortunately, I don't have access to an enterprise varient of stackoverflow so I couldn't test it (nor was I aware of the `X-API-KEY` requirement). I'll be happy to review an implementation.

**Comment by dkmiller** [comment]
Thanks, your endorsement is all I was asking for :). I'll work on an implementation for you to review, making sure it includes careful testing and documentation.

**Comment by AWegnerGitHub** [comment]
Going to close this issue. If you've implemented this and have a branch you'd like to get merged into stackapi, I'd love to see it and review it.
