### ISSUE TITLE
Can we publish a wheel to pypi?

### ISSUE THREAD

**Issue by matthewdeanmartin** [AWegnerGitHub/stackapi#46]
It looks like you publish to pypi with this code: https://github.com/AWegnerGitHub/stackapi/blob/602d9ce6de4b8a3e0462576365536c99a5a14c71/fabfile.py

If you could add bdist_wheel as well as sdist that would be a huge help to folk who for policy reasons would like to only install wheels.

Here are some more [instructions on how to create wheels,](https://www.realpythonproject.com/how-to-create-a-wheel-file-for-your-python-package-and-import-it-in-another-project/), or you could use `poetry build` which is even easier once you've started using poetry.

Thanks for publishing stackapi, I've had a lot of fun hacking with it.

**Comment by AWegnerGitHub** [comment]
Starting with version 0.3.0 there have been wheels available: https://pypi.org/project/StackAPI/0.3.1/#history

Hopefully this helps!

**Comment by matthewdeanmartin** [comment]
Thanks!
