### ISSUE TITLE
How to fetch all the question of a particular tag from stackexchange api?

### ISSUE THREAD

**Issue by monk1337** [AWegnerGitHub/stackapi#47]
I am trying to fetch all the questions tagged on a particular tag from StackExchange API. For example, I want to fetch all questions under the "swift" tag from the "StackOverflow" API.

I am using StackAPI in python but am not able to find a solution on how to fetch all questions automatically?

What I have tried:

The first solution: give a large page number so it will fetch all questions under that limit?

```
    from stackapi import StackAPI
    
    SITE     = StackAPI('stackoverflow')
    SITE.page_size = 100
    SITE.max_pages = 5000000    #very large max_pages number 
    posts    = SITE.fetch('questions', tagged='swift', sort='activity', order = 'desc')
```

That doesn't seem like an optimal solution, this second solution:

  ```
  def stackapi_questions():
      SITE     = StackAPI('stackoverflow')
      posts    = SITE.fetch('questions', tagged='swift', sort='activity', order = 'desc')
      return posts
    
    
    
    def get_all_questions():
    
      has_more = True
      results  = []
      while has_more:
        response = stackapi_questions()
        results.append(response)
        has_more = response['has_more']
      return results
```

Here I am worried to do I need to take care of `'quota_remaining'` and `'backoff'` if I am using StackAPI in this way or do I have to handle those parameters' value myself?

How to fetch all questions using this API or any other better method?

**Comment by monk1337** [comment]
@AWegnerGitHub Please take a look!

**Comment by monk1337** [comment]
@AWegnerGitHub  I tried to write my own function, Please check if it's correct or I can improve it?


```
def fetch_question(page_size = 1):
    
    api_res   = f"https://api.stackexchange.com/2.3/questions?page={int(page_size)}&pagesize=100&order=desc&sort=activity&tagged=swift&site=Stackoverflow&filter=!*MZqiH2lVtmP*wBz"
    response  = requests.get(api_res, verify = False)
    return response.json()





def get_all_questions():
        
    page_count        = 1
    api_init          = fetch_question(page_count)
    page_count+=1

    has_more          = api_init['has_more']
    quota_max         = api_init['quota_max']
    quota_remain      = api_init['quota_remaining']
    total             = api_init['total']
    items_count       = 100


    while has_more:

        if quota_remain == 1:
            """If exhausted quota then sleep for one day 
            to reset the quota limit"""
            
            time.sleep(3600)

        
        elif 'backoff' in api_init:
            """Respect API backoff time"""
            
            backoff = int(api_init['backoff'])
            time.sleep(backoff+1)

        else:
            api_init     = fetch_question(page_count)
            has_more     = api_init['has_more']
            quota_remain = api_init['quota_remaining']

            count_+=100
            page_count+=1
            
            """One second break after each api call to not overload requests"""
            time.sleep(1)


    return {'total_fetched'       : items_count,
            'api_total'           : total} 
```

**Comment by AWegnerGitHub** [comment]
This seems reasonable.

One thing you should check for is how quickly `quota_remaining` changes. I have a vague recollection that it does not always drop by 1, which means your `== 1` could be missed. To be safe, I'd change that to `<= 1`.

**Comment by AWegnerGitHub** [comment]
This seems reasonable.

One thing you should check for is how quickly `quota_remaining` changes. I have a vague recollection that it does not always drop by 1, which means your `== 1` could be missed. To be safe, I'd change that to `<= 1`.

Even [SmokeDetector](https://github.com/Charcoal-SE/SmokeDetector), a _heavy_ SE API user (but not via this library), gives itself a buffer of 20 API calls before hitting 0. https://github.com/Charcoal-SE/SmokeDetector/blob/20520b448eba01661cbefb1f75f47391fcb19a3a/bodyfetcher.py#L32

**Comment by monk1337** [comment]
Thanks for the suggestion, I'll use `<= 1`

**Comment by monk1337** [comment]
After fetching list of questions and corresponding ids, What is the best way to fetch all answers of each question?

**Comment by AWegnerGitHub** [comment]
You'll can use [`/questions/{ids}/answers`](https://api.stackexchange.com/docs/answers-on-questions) with the list of question IDs and a filter that includes the `body`

**Comment by monk1337** [comment]
I just found out that you can get questions and all answers to that particular question from a single API request, while before, I was planning to fetch all questions and then send question ids to fetch all answers to each question.

**Comment by AWegnerGitHub** [comment]
Going to reclose this issue. If you need more support, please open a new issue.
